name: Release

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build 1.16 version
        run: ./gradlew :modget-1.16:build --stacktrace

      - name: Build 1.17 version
        run: ./gradlew :modget-1.17:build --stacktrace

      - name: Build 1.19 version
        run: ./gradlew :modget-1.19:build --stacktrace

      # - name: Upload GitHub release
      #   uses: AButler/upload-release-assets@v2.0
      #   with:
      #     files: "**/build/libs/*.jar;!**/build/libs/*-sources.jar;!**/build/libs/*-dev.jar;!modget-core/"
      #     repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish 1.16 version
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: 2NpFE0R3
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-id: 533960
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          files-primary: modget-1.16/build/libs/!(*-@(dev|sources)).jar
          name: 0.4.4-beta.2 for MC 1.16
          version: 0.4.4-beta.2+1.16
          version-type: beta
          loaders: |
            fabric
          dependencies: |
            fabric-api    | depends
            cloth-config  | recommends
            modmenu       | recommends

      - name: Publish 1.17 version
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: 2NpFE0R3
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-id: 533960
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          files-primary: modget-1.17/build/libs/!(*-@(dev|sources)).jar
          name: 0.4.4-beta.2 for MC 1.17 and 1.18
          version: 0.4.4-beta.2+1.17
          version-type: beta
          loaders: |
            fabric
          game-versions: |
            1.17
            1.17.1
            1.18
            1.18.1
          dependencies: |
            fabric-api    | depends
            cloth-config  | recommends
            modmenu       | recommends

      - name: Publish 1.19 version
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: 2NpFE0R3
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-id: 533960
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          files-primary: modget-1.19/build/libs/!(*-@(dev|sources)).jar
          name: 0.4.4-beta.2 for MC 1.19
          version: 0.4.4-beta.2+1.19
          version-type: beta
          loaders: |
            fabric
          dependencies: |
            fabric-api    | depends
            cloth-config  | recommends
            modmenu       | recommends
